### ISSUE TITLE
Improve: SABnzbd as a Windows Service

### ISSUE THREAD

**Issue by daneyuleb** [sabnzbd/sabnzbd.github.io#10]
## URL: /wiki/advanced/sabnzbd-as-a-windows-service.html

Improvement:

1. List where the "ini" file is--or at least give some hint. ("The ini file is called sabnzbd.ini and is in the SABNZBD folder within your %LOCALAPPDATA% folder" would suffice.  I understand the concept of "if they can't figure it out, they shouldn't be installing it" but it is basic documentation 101 not to make people waste time determining a program's arbitrary nomenclature and settings locations.

2. Make it more clear that the helper service needs to be installed for automatic startup--and reference it earlier in the instructions--not AFTER the "start-stop" and "update" commands which most people don't need if they got to this page to simply install SABNZBD as a always-on service, and thus skim over (don't need to do that, so I'm done I guess).  So the actual, necessary Helper part gets missed--as can be seen by the many confused forum posters out there wondering why it didn't start automatically.  There's even a sentence in the Helper section that says "The service SABHelper will be created automatically when installing the service" which is extremely misleading and ambiguously stated--it's not at all clear if the Helper must be installed or not.

**Comment by jeffgeorge** [comment]
These instructions have been pretty much untouched for years, the only changes we've made since moving the site / wiki to GitHub have been formatting / consistency related.

Personally, it's been years since I've run SABnzbd on Windows, and when I did I didn't run it as a service. You sound pretty knowledgeable on the subject, would you like to take a stab at a full re-write of these service setup instructions? If you provide the raw text we can handle styling it up.

**Comment by Safihre** [comment]
@daneyuleb Yes indeed it probably needs a proper re-write.
Would you be willing to help us?
Can send me an email at safihre@sabnzbd.org!

**Comment by daneyuleb** [comment]
I can give it a shot--I'm not exactly an expert, but I'll send you a rewrite draft...
