### ISSUE TITLE
Quick Install Guide instruction for PPA?

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd.github.io#156]
@jcfp 

Can we make https://sabnzbd.org/wiki/installation/install-ubuntu-repo easier by introducing a "Quick Install Guide".

On Ubuntu 20.04 and higher, I just 
sudo add-apt-repository ppa:jcfp/ppa
and update Ubuntu / install sabnzbd, and it works.

So I just skip the first steps, as on Ubuntu 20.04 those requirements are fullfillled. And I skip "ppa:jcfp/sab-addons" because sabyenc is provided too.

So, at the beginning of the page, introduce:

**Quick Install Guide (Ubuntu 20.04 and higher)**

```
sudo add-apt-repository ppa:jcfp/nobetas
sudo apt-get update && sudo apt-get dist-upgrade
sudo apt-get install sabnzbdplus
```

**Comment by jcfp** [comment]
Totally fine with me, your proposal should work fine on a typical desktop system.

The sabyenc/addons part is on that page indeed outdated, so let's get rid of that.

**Comment by sanderjo** [comment]
OK, I've introduced a **Quick Install Guide for Ubuntu Desktop 20.04 and higher**

Questions 
* is `apt-get` still preferred above `apt`?
* why the` sudo apt-get dist-upgrade` and not a normal upgrade ?

**Comment by sanderjo** [comment]
> The sabyenc/addons part is on that page indeed outdated, so let's get rid of that.

Just remove it? Also not needed anymore for multicore par2?

**Comment by jcfp** [comment]
Apt or apt-get doesn't matter. The regular par2 is itself multicore since a long time using code from what used to be par2-mt. These days, the only choice is between par2 (slower than tbb but with recent updates and bug fixes) and par2-tbb (faster but a decade behind in terms of bug fixes/features).

Using` dist-upgrade` is essential though: the regular `upgrade` will refuse to install extra packages which blocks any sab version that adds new dependencies.

**Comment by Safihre** [comment]
@sanderjo / @jcfp  this is resolved now right?

**Comment by sanderjo** [comment]
AFAIK: yes, because:
- quick install
- old stuff about addons gone
