### ISSUE TITLE
Improve: Install SABnzbdon a NAS

### ISSUE THREAD

**Issue by themanrite** [sabnzbd/sabnzbd.github.io#198]
i need instruction for asustor system

**Comment by Safihre** [comment]
@clintonhall can we just link to this page?
https://www.asustor.com/nl/app_central/app_detail?id=98&type&model=

Is there some limitation, as in that a range of models is not supported by this app?

**Comment by Safihre** [comment]
@clinton-hall can we just link to this page?
https://www.asustor.com/nl/app_central/app_detail?id=98&type&model=

Is there some limitation, as in that a range of models is not supported by this app?

**Comment by clinton-hall** [comment]
should be fine to link to that... I note that that page is specifically for the Netherlands.... but the link changes based on your country/language e.g. https://www.asustor.com/en-gb/app_central/app_detail?id=98&type&model=

At this stage all Currently supported (by Asustor) NAS models are supported.

**Comment by themanrite** [comment]
im not using the plus version

**Comment by clinton-hall** [comment]
The App maintained by Patrick uses docker. You need to install docker, install SABnzb and then configuration would be as per docker. You may need to add path mappings to the docker depending on your setup.

The SABnzbdplus app uses entware and venv. Once installed (install entware and then sabnzbdplus) this should have access to existing paths and can be configured as per normal Sab config instructions.

**Comment by clinton-hall** [comment]
To clarify here. There are 2 SABnzbd apps available on Asustor.
https://www.asustor.com/en-gb/app_central/search_app?model=&keyword=SABnzbd

The App called SABnzbd is available on some NAS models and is maintained by another dev. This uses linuxserver/sabnzbd.

The App called SABnzbdplus was originally created by JohnnyFive and then I took over maintenance of the App. This was originally designed to work with the Git and Python (2) Apps... I don't know the specific history as to why the "plus" was used in the App Name.
More recently the App has been updated to use Entware, the latest (available via Entware) Python and the required Python modules installed via pip. The App runs in its own virtual environment to try and isolate it from other binary/library updates.

Both Apps should allow for automatically updating SABnzbd to the latest version. Don't worry about the naming... they are both Apps for SABnzbd.

Which you use comes down to availability for you NAS model (some don't support Docker) and what your preference is.

When building the App I explored docker. Ultimately this requires the App developer to pre-guess your likely paths/shares to map, and also, since there is a docker GUI app for Asustor I figured anyone who knows docker can install their own without the need for a dev to package as an App... but that was just my opinion... obviously Patrick has since created the Docker version of the App so you have options.

All that said. If you have specific questions about SABnzbdplus App, I can try and help. For the SABnzbd app, you can try the Asustor forums, or email Patrick (his email is linked from the App details page).

Otherwise general questions about config settings for SABnzbd should be common to both Apps themselves. Start with the wiki here https://sabnzbd.org/wiki/

**Comment by Safihre** [comment]
Thanks for explaining. I linked both from our page now with the added note that the SABnzbd-package uses Docker and is not supported on all models. 
https://sabnzbd.org/wiki/installation/install-nas
Just wondering if maybe in your next update you can also update the icon? We haven't used the 3D-version for a number of years now. Not high priority of course 🥇
