### ISSUE TITLE
Improve: Fedora and RHEL/CentOS/Scientific Linux RPM

### ISSUE THREAD

**Issue by lqlarry** [sabnzbd/sabnzbd.github.io#209]
## URL: /wiki/installation/install-fedora-centos-rhel.html

Improvement:
Information is 6 years old. Website link says good for Fedora 33 and Fedora is about to release Fedora 36.

It would be nice to have a Flatpak.

**Comment by Safihre** [comment]
Can you help us update the info? None of us are fedora users.

After the disaster that is Snaps, I'm extremely reluctant to support another Linux packaging system...

**Comment by lqlarry** [comment]
Sure, I'll try to help.  Sabnzbd is easily available on Debian, Ubuntu & Slackware (not really maintained on Slackware).  Arch is hit and miss and Snaps are the only way to get Sabnzbd on Linux.

**Comment by lqlarry** [comment]
What info do you need?  I'm not much on programming and I got lost in Flatpaks so I can't build it.

**Comment by Safihre** [comment]
What I meant was: if the current information is incorrect, what is the correct way? Because we don't know since we don't use the OS.

**Comment by jcfp** [comment]
There's https://www.nosuchhost.net/~cheese/fedora/packages/ALL/x86_64/SABnzbd.html but since I haven't used anything rpm-based in ages I'm not in a position to test anything and hesitant to put it on the wiki just that.

Anyone familiar with that repo or willing to try it out, please leave a comment. Reputation, package quality, etc? @lqlarry
