### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd.github.io#25]
* does this need to be updated from 0.7 to 2.0:
https://github.com/sabnzbd/sabnzbd.github.io/blob/master/_config.yml#L17

* how do you make changes to sab wiki offline to know what they look like/work?
as trying to make any changes 'offline' its a royal pain as the header/footer/layout is not loaded.. 
looking online people mention of installing ruby+jekyll/gollum to work on github wiki pages offline before pushing... but I failed to get this working on windows (which apparently is a known issue on getting gollum installed due to a ruby dependency that doesnt like windows)

**Comment by Safihre** [comment]
> does this need to be updated from 0.7 to 2.0:

Oops, old leftover code. Deleted now.

Getting it working on Windows was annoying, but this site has it all:
http://jekyll-windows.juthilo.com/1-ruby-and-devkit/
You need that devkit and set it up, otherwise it won't continue.
Worth noting is that installing is slow and sometimes it seems to hang and do nothing, but then magically continues.

And then you can just run in the repo:
`jekyll serve -i` (incremental makes it much faster. It will complain about some missing gem, if you install that gem the CPU usage will reduce a lot)

**Comment by thezoggy** [comment]
thanks Safihre, got it working!

for those that find this, if you spin up a vm to store the source+run ruby but want to actually access it from your phone/another box you need to do: `jekyll serve -i --host 0.0.0.0`

**Comment by Safihre** [comment]
Looking forward to those PRs :+1: 
The wiki is so big, it's easy to miss pages or switches etc..

**Comment by shypike** [comment]
Jekyll told me to add this too:
`gem install jekyll-redirect-from`
otherwise it refused to run.

**Comment by thezoggy** [comment]
new machine, been awhile since i messed with the wiki and needed to preview.

installed ruby+debkit, 
gem install jekyll bundler

then went to serve up content but had to install a few other gem's first:

gem install jekyll-redirect-from
gem install wdm
gem install webrick

then could serve up pages just fine:
jekyll serve -i --host 0.0.0.0

at http://127.0.0.1:4000/

**Comment by Safihre** [comment]
If you just install the github-pages gem, it includes everything!

**Comment by thezoggy** [comment]
I tried that at one point but man does it install a lot of stuff, then I saw people talking about how you shouldn't install more gem's than you need to as it slows things down.. unless you do a gemfile which we dont for our repo to limit whats loaded
